
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# important for traefik to work
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - '172.20.0.0/16'  # got this from logs of homeassistant container
    - 127.0.0.1
    - ::1
