
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !env_var RECORDER_DB_URL
  # purge_keep_days: 10
  # exclude:
  #   domains:
  #     - camera
  #     - device_tracker

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# important for traefik to work
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - '172.20.0.0/16'  # got this from logs of homeassistant container
    - 127.0.0.1
    - ::1
